In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv(r"D:\AIML_MSIS\Applied Machine Learning\Lab_programs\August_18\bestsellers with categories.csv")

In [ ]:
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
#split indepedent variable
df
x=df.iloc[:, 2 :-1].values
x

array([[4.7000e+00, 1.7350e+04, 8.0000e+00, 2.0160e+03],
       [4.6000e+00, 2.0520e+03, 2.2000e+01, 2.0110e+03],
       [4.7000e+00, 1.8979e+04, 1.5000e+01, 2.0180e+03],
       ...,
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0170e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0180e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0190e+03]], shape=(550, 4))

In [6]:
#dpilt dependent variable
y=df.iloc[:,-1].values
y

<StringArray>
['Non Fiction',     'Fiction', 'Non Fiction',     'Fiction', 'Non Fiction',
     'Fiction',     'Fiction',     'Fiction', 'Non Fiction',     'Fiction',
 ...
     'Fiction',     'Fiction',     'Fiction',     'Fiction',     'Fiction',
     'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction']
Length: 550, dtype: str

In [7]:
#taking care of missing data
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy ='mean')
imputer =imputer.fit(x[:,2:5])
x[:,2:5] =imputer.transform(x[:,2:5])
x
#Nan is for the numerical data col

array([[4.7000e+00, 1.7350e+04, 8.0000e+00, 2.0160e+03],
       [4.6000e+00, 2.0520e+03, 2.2000e+01, 2.0110e+03],
       [4.7000e+00, 1.8979e+04, 1.5000e+01, 2.0180e+03],
       ...,
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0170e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0180e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0190e+03]], shape=(550, 4))

In [8]:
#encoding the categoricaL data
#from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#labelencoder_X=LabelEncoder()
##x[:,0]=labelencoder_X.fit_transform(x[:, ])
x

array([[4.7000e+00, 1.7350e+04, 8.0000e+00, 2.0160e+03],
       [4.6000e+00, 2.0520e+03, 2.2000e+01, 2.0110e+03],
       [4.7000e+00, 1.8979e+04, 1.5000e+01, 2.0180e+03],
       ...,
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0170e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0180e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0190e+03]], shape=(550, 4))

In [9]:
#from sklearn.compose import ColumnTransformer 
#from sklearn.preprocessing import OneHotEncoder

# This targets ONLY the Genre column (index 6)
#ct = ColumnTransformer([("Genre", OneHotEncoder(), [6])], remainder="passthrough")
#x = ct.fit_transform(x)
#x


In [10]:
print("Features array shape:", x.shape)
print("Encoded Target array:", y[:5])

Features array shape: (550, 4)
Encoded Target array: <StringArray>
['Non Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Non Fiction']
Length: 5, dtype: str


In [11]:
#Encoding the Dependent variable

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_y =LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,

In [12]:
#split the data into training and testing
#test_size=0.2 -> training 80%, testing %20
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=45)
#X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [13]:
X_test
#X_test.astype(int)

array([[4.6000e+00, 1.9720e+04, 8.0000e+00, 2.0090e+03],
       [4.8000e+00, 2.9673e+04, 1.6000e+01, 2.0100e+03],
       [4.7000e+00, 1.0820e+04, 5.0000e+00, 2.0180e+03],
       [4.9000e+00, 1.9546e+04, 5.0000e+00, 2.0130e+03],
       [4.5000e+00, 7.2000e+02, 1.0000e+00, 2.0090e+03],
       [4.7000e+00, 4.3700e+03, 1.5000e+01, 2.0160e+03],
       [4.9000e+00, 8.8420e+03, 1.0000e+01, 2.0170e+03],
       [4.6000e+00, 6.9900e+03, 4.0000e+00, 2.0130e+03],
       [4.8000e+00, 1.8613e+04, 5.0000e+00, 2.0140e+03],
       [4.8000e+00, 3.9230e+03, 1.6000e+01, 2.0180e+03],
       [4.8000e+00, 2.6630e+03, 1.7000e+01, 2.0130e+03],
       [4.7000e+00, 2.3308e+04, 6.0000e+00, 2.0150e+03],
       [4.5000e+00, 4.3800e+02, 1.5000e+01, 2.0090e+03],
       [4.7000e+00, 2.2614e+04, 1.1000e+01, 2.0120e+03],
       [4.8000e+00, 1.0922e+04, 5.0000e+00, 2.0160e+03],
       [4.3000e+00, 1.9240e+03, 8.0000e+00, 2.0100e+03],
       [4.3000e+00, 1.3616e+04, 1.0000e+01, 2.0120e+03],
       [4.7000e+00, 2.5001e+04,

In [14]:
X_train

array([[4.8000e+00, 2.3047e+04, 6.0000e+00, 2.0180e+03],
       [4.8000e+00, 1.4038e+04, 4.0000e+00, 2.0170e+03],
       [4.8000e+00, 8.8370e+03, 5.0000e+00, 2.0190e+03],
       ...,
       [4.4000e+00, 1.5526e+04, 1.4000e+01, 2.0160e+03],
       [4.8000e+00, 2.1625e+04, 9.0000e+00, 2.0170e+03],
       [4.7000e+00, 9.2890e+03, 9.0000e+00, 2.0120e+03]], shape=(440, 4))

In [15]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [16]:
X_test

array([[-1.08861812e-01,  6.48020559e-01, -4.77447139e-01,
        -1.55580274e+00],
       [ 7.62032687e-01,  1.49054600e+00,  2.78904764e-01,
        -1.24407542e+00],
       [ 3.26585437e-01, -1.05368009e-01, -7.61079102e-01,
         1.24974319e+00],
       [ 1.19747994e+00,  6.33291389e-01, -7.61079102e-01,
        -3.08893440e-01],
       [-5.44309062e-01, -9.60337058e-01, -1.13925505e+00,
        -1.55580274e+00],
       [ 3.26585437e-01, -6.51363095e-01,  1.84360776e-01,
         6.26288535e-01],
       [ 1.19747994e+00, -2.72806502e-01, -2.88359163e-01,
         9.38015860e-01],
       [-1.08861812e-01, -4.29579045e-01, -8.55623090e-01,
        -3.08893440e-01],
       [ 7.62032687e-01,  5.54312565e-01, -7.61079102e-01,
         2.83388477e-03],
       [ 7.62032687e-01, -6.89201824e-01,  2.78904764e-01,
         1.24974319e+00],
       [ 7.62032687e-01, -7.95861329e-01,  3.73448752e-01,
        -3.08893440e-01],
       [ 3.26585437e-01,  9.51746197e-01, -6.66535115e-01,
      